### ISSUE TITLE
Support for Ports other than 3000

### ISSUE THREAD

**Issue by krusesw** [krumiaa/MindMaker#2]
I need to be able to run 2+ separate instances of MindMaker on a single project at the same time. How do I accomplish this?

**Comment by krumiaa** [comment]
Working on this, will post back shortly with an update

**Comment by krusesw** [comment]
Thank you so much :)

**Comment by krumiaa** [comment]
Ok, have updated the Remote ML server example files and github documentation demonstrating how to create multiple clients. 

In short,  to add a second learning agent(or more) to your map, you will need all the same functions that are in the first learning agent, the launch mindmaker blueprint node etc, but instead of assigning this one to port 3000  you will assign it port 3001 in blueprints. Besides changing the socketio port setting in blueprints, you will also need to to change the Connect SocketIO blueprint function, modifying the In Address and Port to the new number you have created “http://localhost:3001” for instance.  

Than you will just need to create a second instance of your mindmaker_client.py file that will connect to your second learning agent. Training can be done simultaneously, in parallel. The only modification that you need to make to mindmaker_client.py is changing  sio.connect('http://localhost:3000') at the bottom of the file to sio.connect('http://localhost:3001') or whatever is the number of new learning agents you are working with. If you have five learning agents, than you will have five instances of the client running and each will have a new port number all the way up to 3005.

I added all this in the main documentation, if its not clear, I will consider making a video tutorial or something along those lines.
