### ISSUE TITLE
When are the chosen actions supposed to be executed?

### ISSUE THREAD

**Issue by FLOROID** [krumiaa/MindMaker#9]
Hello there ^^

I am currently trying to set up my AI Agent for Autonomous Driving.
I've set up my Make Observations Functio and the Check Reward function and I am now wanting to bind the actions chosen by the Algorithm to their respective actions in unreal engine. For example having the action with the iterator 1 increase the throttle of the car. 
Now I'm trying to figure out when to do that. Do I execute those actions inside the Receive Action function before Observations are made using the "Action Selected" Integer Value? Also, does the range of values for Action Selected start at 0?

And as a final question - does the Mindmaker executable automatically call the Receive Action function or do I have to call it anywhere because I couldn't find any place in the example project where the function was being called?

Best regards,

Flo

**Comment by krumiaa** [comment]
Actions will automatically begin executing once the launch mindmaker function commences, eg at the beginning of gameplay. The executable itself will start choosing random actions according to whatever action space you specified in the launch mindmaker function, so you will want to define this exactly as you want your actions to be received. Actions are then received in the receive actions function, where you can define how those actions will actually show up and be displayed in game play. Before that it will just be some numeric representation in an array, as you defined in the action space variable of the launch mindmaker function.
The Mindmaker executable doesn’t itself automatically call the receive actions function, but in all the blueprint examples Ive made there is some initial nodes immediately prior to the launch mindmaker blueprint function which define the conditions for calling receive action function, so that once the mindmaker executable starts generating actions, these automatically trigger the receive actions function to start. So in effect it gets automatically done once the executable begins producing actions.

Once you get farther along with your self driving game, would you be open to sharing it as a mindmaker example?  I think it would be really useful for others trying to get their hands dirty with this stuff.

**Comment by FLOROID** [comment]
I apologize for the delayed reply.

I'll have a look into my blueprint functions in a bit to see if I can find my error, because at the moment, the MindMaker executable only manages to establish a connection to UE, however nothing else happens yet after that point.

Also - regarding your question: I would be more than happy to do so. I'm documenting the process of making my own Blueprint Actor using the example project. I am also using Unreal Engines Vehicle Template Content, so that it's easy to replicate. Once I'm done with my paper I can write an english documentation that you can reference together with the project, which I will happily supply to you :)

**Comment by FLOROID** [comment]
I believe the connection to MindMaker is correctly being established.
![image](https://user-images.githubusercontent.com/58942125/150371702-b0fc510c-7602-4c4f-9a47-4a93e569aa88.png)
This is the Output, that I can see in the executable. After that, nothing else happens.

Is the Action Space Array ever passed to Mindmaker and therefore relevant to it? And what exactly is it used for inside the Receive Action function? It's a little hard to decipher for me.

As for the Observation Space Shape, I assume the syntax works like this: action 0 has low bounds in the low array at the iterator 0 and high bounds in the high array at the iterator 0. Meaning that for let's say 3 actions with low bounds of 0.0f and high bounds of 100.0f the string would look like this **low=np.array([0,0,0]), high=np.array([100,100,100]),dtype=np.float32**
Is that correct?

Another small question would be, if the number of pins on the set members in custom stuct node influences the message that is being generated by the Json Object.
In the example project (inside the Send Observations function) it looks like this
![image](https://user-images.githubusercontent.com/58942125/150377737-0f71c34c-558d-49fd-84f9-7d0bb6dfa8d8.png)

however in my own project, the Set members in MindMakerCustStrucStart functions automatically splits into all the available pins. Does that influence the result in any way? And if so, does simply removing the pins change anything about that?

![image](https://user-images.githubusercontent.com/58942125/150377991-369a0b91-5ddb-4e79-bded-f09da072fdfd.png)

**Comment by krumiaa** [comment]
Action space, observation space etc are all passed to mindmaker learning engine and are essential for configuring the environment. Refer to the OpenAI gym documentation and stable baselines documention for more on each of those. https://stable-baselines.readthedocs.io/en/v2.10.0/guide/custom_env.html
The number of pins doesnt influence the results, you can choose to show the available pins as a setting within UE, thats all. Since only reward and observations are passed back to the learning engine on a reoccurring basis, those are the only pins displayed in the example.

**Comment by krumiaa** [comment]
Hi Florian,

I know the learning curve can be pretty steep when you're just getting
started with this ML stuff, and the openai and stable baselines
documentation is pretty dense. You could also try a book like this to get
started.

https://www.amazon.com/dp/1839214937?tag=uuid10-20

As for your particular issues, since youve moved out of the AI controller
BP, I would make sure all of the socket IO plugin stuff has been added to
your blueprint class and the json based communications are working
properly. Once mindmaker has been successfully launched, it should
immediately begin sending actions to unreal engine. As such, I would make
sure all the bindings immediately following the event begin play in the AI
controller BP example are present and functioning. This might be a
laborious process of just going through each function(receive action etc)
one by one and making sure the basic communications functionality is
working, then moving on from there.

Not sure what kind of priority you have on this, but if you get stuck and
are considering bringing in outside help to go through your code, I
occasionally consult on such projects. You can email me at
***@***.*** if you're interested.

-Aaron

**Comment by FLOROID** [comment]
Hi Aaron,

I've gotten my hands on the book you recommended and will be digging into that :)

As for the current issues:
I had an extra look through my setup in the Event Graph.

Begin Play executes the Mind Maker Windows function just like it does in the cartpole example, which works just fine. 
The executable launches properly.
On Connected(SocketIOClient) executes the "Bind Event to Function" functions which are configured the same way they are in the cartpole example
![image](https://user-images.githubusercontent.com/58942125/163818444-c407143b-e7fd-4408-81b2-91c60c00907b.png)
The related BP functions are named accordingly
![image](https://user-images.githubusercontent.com/58942125/163818528-832c7c05-6a18-43fd-b81c-9f7df7f990b0.png)
The connect function connects to http://localhost:3000 , which is confirmed in the executable and therefore seems to work just fine. 
I added a SocketIOClient component to the Blueprint, which is also configured the same way it is in the cartpole example.

As for the Launch Mind Maker function, I currently use this setup:
![image](https://user-images.githubusercontent.com/58942125/163819353-ad4398dc-750c-4aa1-9e1b-b94093f71eb2.png)
My MakeObservations function should spit out 6 float values from 0 to 1
and for the action vector I expect an integer value corresponding to the action that should be chosen. 
How should I adjust the Action Space Shape for that?

Regarding your suggestion to double check the "basic communication functionality". What exactly do you mean by this and how would you go about checking this?

Last but not least - I really appreciate your offer for consultation and I would be very happy to take you up on that offer. First, however, I would like to exhaust all other options :)

**Comment by krumiaa** [comment]
The first thing that should happen when the mindmaker executable is launched is it will begin sending actions to blueprints, and if successful, these will show up in the receive action function in UE. So by testing the communications, I mean put in some kind of print node that spits out whatever action is being received, that way you can look at it and makes sure it makes sense in the context of your defined action space. Then go from there, checking that UE is sending o observations and rewards back to mindmaker executable, which if successful will trigger another action to be sent back. I think you may be hitting a snag in how your defining your action space. You have selected a discrete action space, which means the action space should consist of single integer, comprising the number of total actions the agent can take. So you could just put in 7, if you wanted 8 actions(0 is its own action). I have yet to find a good tutorial on creating custom environments in Open AI gym, but this is where that information would be covered. You could try searching the same.

**Comment by FLOROID** [comment]
Thank you very much for the tip regarding the action space shape, I now have an input of 5 into that node for my 6 potential actions. 

I have made some progress and managed to get it to fire the first action!
The Emit Node for the launchmindmaker event (shown below) wasn't firing. I will include this in my documentation as something to check if someone runs into the same issue :)
![image](https://user-images.githubusercontent.com/58942125/164236311-ec8b9e39-a06e-4188-817d-2dba86179843.png)

I'll try to sort out what comes after now and I'll keep you posted :)
